### PR TITLE
deployment-endpoint.yaml: run init_endpoint in loop

### PR DESCRIPTION
**Pull request by liranmauda**
deployment-endpoint.yaml:

when endpoint fails rerun it (and not re-create pod)

### CODE REVIEW

**Comment by nb-ohad** [comment]
I already introduced a similar loop inside the init_endpoints in the bash script in an upcoming PR

Reasoning:
Doing it in the bash script gives us more control like limiting the number of restarts or printing a message to stdout on each restart so we have it in the logs.

**Comment by liranmauda** [comment]
> @liranmauda
> I already introduced a similar loop inside the init_endpoints in the bash script in an upcoming PR
> 
> Reasoning:
> Doing it in the bash script gives us more control like limiting the number of restarts or printing a message to stdout on each restart so we have it in the logs.

@nb-ohad 
Sure, once you open the PR lets take a look and we can close this one

**Comment by liranmauda** [comment]
Converting to draft as this PR might be closed, When @nb-ohad Will open new PR

**Comment by liranmauda** [comment]
@nb-ohad Did you introduced your PR regarding this? 
If not, we might want to merge this one to be able to have it on 2.3

**Comment by nb-ohad** [comment]
Already resolved with noobaa-core PR: 
https://github.com/noobaa/noobaa-core/pull/5977

Please close this one

**Comment by liranmauda** [comment]
> Already resolved with noobaa-core PR:
> [noobaa/noobaa-core#5977](https://github.com/noobaa/noobaa-core/pull/5977)
> 
> Please close this one

Closing

**Comment by guymguym** [comment]
For future reference see here:
https://github.com/noobaa/noobaa-core/blob/5008ac8305941e6c807b31d286bedb089ca061f7/src/deploy/NVA_build/noobaa_init.sh#L72-L84
```
# run_internal_process runs a process and handles NOOBAA_INIT_MODE.
#
# NOOBAA_INIT_MODE allows devs to set how the container behaves when the process exits.
# Possible mode values are:
# - "" (no env/file or empty string) is the default and means to exit the container
# - "auto" restart the process without letting the container die to allow reloading code.
# - "manual" the container will loop and wait for manual intervention to change the mode.
#
# Usage: set env NOOBAA_INIT_MODE on the deployment pod spec
#   or write the value to /root/node_modules/noobaa-core/NOOBAA_INIT_MODE
#   (the file will override the env).
#
run_internal_process() {
    ...
```

**Pull request closed without merging**
