### PR TITLE
CI | Exclude 'docs' Directory From GitHub Workflows 

### PR DESCRIPTION
**Pull request by shirady**
### Explain the changes
1. Add `workflow_dispatch` option where we didn't have it.
2. Exclude `doc` directory from the CI (for more information you can see [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths)).

### Issues: Fixed #xxx / Gap #xxx
1. none

### Testing Instructions:
1. none

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

**Comment by shirady** [comment]
I created an example:
Here you can see 2 PRs: [one with checks](https://github.com/shirady/learn-action/pull/6) (changes outside of `docs`), and one with changes only in `docs` - [no checks](https://github.com/shirady/learn-action/pull/7).
Screenshot 2023-04-18 at 9 43 07

**Comment by shirady** [comment]
@baum, Did you have a reason not to allow `workflow_dispatch` in some of the workflows you worked on?
Please pay attention to this when you review the changes.

**Comment by shirady** [comment]
@nimrod-becker @guymguym, I want to make sure that the renaming (from `doc` to `docs`) would not defect [this site](https://www.noobaa.io/).

**Review by baum — APPROVED** [review]

**Review by liranmauda — APPROVED** [review]
LGTM

**Comment by shirady** [comment]
> @nimrod-becker @guymguym, I want to make sure that the renaming (from `doc` to `docs`) would not defect [this site](https://www.noobaa.io/).

I didn't insert the rename `doc` to `docs` in this PR because it might break external links.

**Pull request merged**
