### PR TITLE
Fixing LC_COLLATE - operator side

### PR DESCRIPTION
**Pull request by jackyalbo**
Signed-off-by: jackyalbo <jalbo@redhat.com>

### Explain the changes
1.  We need to set also collation for the initdb container in order to fix 2068110

### Issues: Fixed #xxx / Gap #xxx
1.  Fixed BZ2068110

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
LGTM

**Review by dannyzaken — CHANGES_REQUESTED** [review]
@jackyalbo it looks good for new installations, but what will happen with existing systems?
AFAIR you cannot just change the LC_COLLATE env for existing DB, so you should at least ignore this env if it doesn't exist. 
For a complete solution, we need to figure out how we to handle existing DBs

**Comment by jackyalbo** [comment]
> @jackyalbo it looks good for new installations, but what will happen with existing systems? AFAIR you cannot just change the LC_COLLATE env for existing DB. For a partial solution that only handles new systems, you should at least ignore this env in existing systems. For a complete solution, we need to figure out how to handle existing DBs

@dannyzaken that won't effect already created DBs. It is relevant only for new databases. BTW, that's why I added this env to both containers as only the one really creates the DB (the init container) changes the collation, having another container with different collation just won't have any effect (but left for both as a good practice)

**Comment by jackyalbo** [comment]
> @jackyalbo it looks good for new installations, but what will happen with existing systems? AFAIR you cannot just change the LC_COLLATE env for existing DB. For a partial solution that only handles new systems, you should at least ignore this env in existing systems. For a complete solution, we need to figure out how to handle existing DBs

@dannyzaken that won't effect already created DBs. It is relevant only for new databases. BTW, that's why I added this env to both containers as only the one really creates the DB (the init container) changes the collation, having another container with different collation just won't have any effect (but left for both as a good practice)

**Review by dannyzaken — APPROVED** [review]

**Pull request merged**
