### PR TITLE
Backport to 2.2

### PR DESCRIPTION
**Pull request by nimrod-becker**

### CODE REVIEW

**Comment by guymguym** [comment]
CI fails on:
```
09:54:24 Starting the delete cycle
INFO[0000] 🗑️  Deleting: ObjectBucketClaim "bucket1"    
INFO[0001] 🗑️  Deleted : ObjectBucketClaim "bucket1"    
INFO[0000] 🗑️  Deleting: BucketClass "bucket.class1"    
INFO[0000] 🗑️  Deleted : BucketClass "bucket.class1"    
NAME          TYPE            TARGET-BUCKET   PHASE   AGE     
compatible1   s3-compatible   first.bucket    Ready   1m18s   
compatible2   s3-compatible   second.bucket   Ready   59s     
09:54:27 Starting the delete related compatible2 paths
...
FATA[0001] ❌ Could not delete BackingStore "compatible2" in namespace "test" as it is being used by one or more buckets 
09:54:29 ✅  build/_output/bin/noobaa-operator-local -n test backingstore delete compatible2 failed - as should
INFO[0000] 🗑️  Deleting: ObjectBucketClaim "bucket4"    
INFO[0001] 🗑️  Deleted : ObjectBucketClaim "bucket4"    
INFO[0000] 🗑️  Deleting: BucketClass "bucket.class4"    
INFO[0000] 🗑️  Deleted : BucketClass "bucket.class4"    
...
INFO[0000] ✅ RPC: bucket.list_buckets() Response OK: took 1.4ms 
09:55:00 ✅  buckets in system: bucket1-d50aad8b-62df-4a5e-9413-01d0b25accdf
...
FATA[0001] ❌ Could not delete BackingStore "compatible2" in namespace "test" as it is being used by one or more buckets 
09:55:02 ❌  build/_output/bin/noobaa-operator-local -n test backingstore delete compatible2 failed, Exiting

09:55:02 ==============OPERATOR LOGS============
...
09:55:03 ==============CORE LOGS============
...
```

**Comment by guymguym** [comment]
@nimrod-becker @dannyzaken So from these logs ^ we can see that the deletion of OBC bucket1 did not remove the bucket itself `bucket1-d50aad8b-62df-4a5e-9413-01d0b25accdf` - need to look on the core logs to figure out why.

**Comment by jackyalbo** [comment]
@guymguym  what version of lib_bucket_provisionser? I guess not latest... I think it's a known issue

**Comment by guymguym** [comment]
@jackyalbo The version in 2.2 branch :)

**Comment by nimrod-becker** [comment]
not the latest, that would come next release

**Pull request merged**
