### PR TITLE
CLI noobaa install yaml - command to dump the install yamls #303

### PR DESCRIPTION
**Pull request by baum**
### Testing Instructions:
Run the following on clean k8s cluster:
- `noobaa --mini=true install yaml  1> install.yaml`
- `kubectl create -f install.yaml`

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
LGTM,
Just one mark, we need to remember to remove it on the DS

**Comment by nimrod-becker** [comment]
@liranmauda true

**Review by dannyzaken — APPROVED** [review]

**Comment by dannyzaken** [comment]
@liranmauda why do we need to remove it DS?

**Comment by liranmauda** [comment]
> @liranmauda why do we need to remove it DS?

@dannyzaken  The DS CLI does not support `install` and `uninstall`.
As we hide the `install` and `uninstall` CLI command we would like to avoid dumping the yamls (which will ease the installation of noobaa using `kubectl create -f install.yaml`)

With that said, as this command only dumps the yamls, do you see value in keeping it in the DS CLI (for analyzing maybe)?

@dannyzaken @guymguym @baum WDYT?

**Comment by nimrod-becker** [comment]
We can keep it, I don't see the harm in it

**Pull request merged**
