### PR TITLE
Updating minikube version

### PR DESCRIPTION
**Pull request by liranmauda**
- Update minikube version to 1.8.2
- Update kubernetes version to 1.17.3
- Installing conntrack
- Added MINIKUBE_DEBUG="--alsologtostderr --v=5" commented out by default
- removed the "--extra-config=apiserver.authorization-mode=RBAC" flag as it no longer needed in kubernetes 1.17 and up

### CODE REVIEW

**Comment by liranmauda** [comment]
Currently failing due to https://github.com/kubernetes/minikube/issues/7058

**Comment by guymguym** [comment]
@liranmauda Are you sure this is the same issue from minikube? In our case we use `minikube config set vm-driver none` and in the issue it was virtualbox.

Perhaps with vm-driver none the issue is that minikube doesn't support the os dist we define here: https://github.com/noobaa/noobaa-operator/blob/master/.travis.yml#L1-L2

I would look for issues with ubuntu xenial and driver none.

**Comment by guymguym** [comment]
Here are the minikube docs for driver none:
https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by guymguym** [comment]
Check out this example:
https://github.com/lilic/travis-minikube/blob/master/.travis.yml

**Comment by liranmauda** [comment]
in the example above, they use kubectl 1.18.1, let's try that.

**Comment by guymguym** [comment]
Still failing but I see this info - seems like the only error is that you need to install `conntrack`
```
W0506 11:14:28.324671    5132 exit.go:101] Error starting cluster: init failed. output: "

-- stdout --
[init] Using Kubernetes version: v1.18.1
[preflight] Running pre-flight checks

-- /stdout --

** stderr ** 
W0506 11:14:27.469164    5265 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
    [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
    [WARNING FileExisting-ebtables]: ebtables not found in system path
    [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
    [ERROR FileExisting-conntrack]: conntrack not found in system path
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
** /stderr **

"
: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.1:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": exit status 1
```

**Comment by guymguym** [comment]
@liranmauda add `sudo apt-get -y install conntrack` like we see here:
https://github.com/lilic/travis-minikube/blob/08db8c0e32217a6f42a4de2ae6b86b1ec638526f/.travis.yml#L14

**Comment by liranmauda** [comment]
@guymguym already did, it failed.
lets try change the distro to ubuntu bionic ?

**Comment by guymguym** [comment]
Can you add `--v=5` like they suggest?

**Comment by guymguym** [comment]
Also worth trying minikube version 1.8.1 like in the minikube-travis example

**Comment by guymguym** [comment]
Check this out - 11 days ago - https://github.com/kubernetes/minikube/issues/7905

**Comment by guymguym** [comment]
@liranmauda OK ignore previous link, but I think this one might be the issue:
https://github.com/kubernetes/minikube/issues/6061

Here is the solution from it:
>Notice this warning:
>W1211 16:40:12.204626 4562 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "RBAC"

>If you really want to specify particular modes, please use --extra-config=apiserver.authorization-mode=Node,RBAC with Kubernetes v1.17.x and newer.

**Comment by guymguym** [comment]
@liranmauda How about trying to remove that extra-config flag altogether?

**Comment by liranmauda** [comment]
> @liranmauda How about trying to remove that extra-config flag altogether? I don't think we need it on new kubernetes (not sure, but worth trying)

ho, i thought so but first pushed with `--extra-config=apiserver.authorization-mode=Node,RBAC`

**Comment by guymguym** [comment]
@liranmauda The tests are still running but minikube start finally worked!

**Comment by guymguym** [comment]
I am pretty sure you can remove this flag, and revert the dist change and also update to latest versions you wanted to use, and run again..

**Comment by liranmauda** [comment]
It is looping on 
```
+ main@.travis/install-minikube.sh:49 kubectl get pods --all-namespaces

NAMESPACE     NAME                                                                      READY   STATUS             RESTARTS   AGE

kube-system   coredns-66bff467f8-s6w9v                                                  0/1     CrashLoopBackOff   6          7m11s

kube-system   coredns-66bff467f8-tzdpn                                                  0/1     CrashLoopBackOff   6          7m11s

kube-system   etcd-travis-job-7f17877f-c6d3-455a-8a2b-3b151eff4bd4                      1/1     Running            0          7m18s

kube-system   kube-apiserver-travis-job-7f17877f-c6d3-455a-8a2b-3b151eff4bd4            1/1     Running            0          7m18s

kube-system   kube-controller-manager-travis-job-7f17877f-c6d3-455a-8a2b-3b151eff4bd4   1/1     Running            0          7m18s

kube-system   kube-proxy-fnm4b                                                          1/1     Running            0          7m11s

kube-system   kube-scheduler-travis-job-7f17877f-c6d3-455a-8a2b-3b151eff4bd4            1/1     Running            0          7m18s

kube-system   storage-provisioner                                                       1/1     Running            0          7m17s
```

**Comment by guymguym** [comment]
@liranmauda It waits for kube-addon-manager. I think this check is unneeded:
https://github.com/noobaa/noobaa-operator/blob/6553511421708c39acf112671099e1419ff19943/.travis/install-minikube.sh#L48-L49

**Comment by guymguym** [comment]
You can update the checks after minikube start to match these:
https://github.com/lilic/travis-minikube/blob/08db8c0e32217a6f42a4de2ae6b86b1ec638526f/.travis.yml#L28-L36

**Comment by guymguym** [comment]
The two last steps in that script are irrelevant to us, because they try to deploy a redis pod, so that's not needed. But the first two are relevant:
```
# Following is just to demo that the kubernetes cluster works.
- kubectl cluster-info
# Wait for kube-dns to be ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to be available"; kubectl get pods --all-namespaces; done
```

**Comment by guymguym** [comment]
failed on `MINIKUBE_DEBUG unbound variable` - you need to set it to empty by default, and no need to export it.

**Comment by liranmauda** [comment]
is this relevant? 
```
# Create example Redis deployment on Kubernetes.
- kubectl run travis-example --image=redis --labels="app=travis-example"
```

**Comment by guymguym** [comment]
Not relevant - I tried to write about it in [this previous comment](https://github.com/noobaa/noobaa-operator/pull/301#issuecomment-624614376)

**Comment by liranmauda** [comment]
Nice the tests started :)

**Comment by guymguym** [comment]
@liranmauda The failure is in test-cli-flow, is it related to the new version?

**Pull request merged**
