### PR TITLE
Reduce indentation in VerifyObjectBucketCleanup()

### PR DESCRIPTION
**Pull request by obnoxxx**
This is another fallout of looking at #309. 
It just struck me that the indentation in `VerifyObjectBucketCleanup()` is unnecessarily deep. This patch reduced it by adding early exits. Look at the patch with `git show -w` to see that it is really minimal. This does not change the behavior at all, just streamlines the code.

Not sure if such a coding style is appreciated in noobaa-operator or not. Just putting it up here for comment.

It is currently based on top of PR #323 since there is a context overlap.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@romayalon @nimrod-becker @dannyzaken - fyi just another non-semantic change ;-)

**Comment by guymguym** [comment]
@obnoxxx Please rebase and squash, thanks

**Comment by obnoxxx** [comment]
@guymguym pushed rebase. 

Questioning squash as these commits are doing two separate but related changes to the function, and it's easier to see in separate commits. But will squash if you insist. :smile:

**Comment by guymguym** [comment]
We tend to squash pretty aggressively in the context of the same change. So yes please.

**Comment by obnoxxx** [comment]
squashed

**Comment by guymguym** [comment]
please rebase and I'll merge

**Comment by obnoxxx** [comment]
rebased

**Pull request merged**
