### PR TITLE
Add disable aggregator field to NooBaa CR and export it as env variable

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

### CODE REVIEW

**Review by dannyzaken — APPROVED** [review]

**Comment by guymguym** [comment]
Why add this to spec?? Is this a valid configuration? If this is just a workaround please keep it off the CR spec.

**Comment by dannyzaken** [comment]
I agree with @guymguym, my hand was easy on the approve. we should control this setting in a different way and not change the CRD.

**Comment by nb-ohad** [comment]
Adding to what Guy has said, a simple env var will do the trick

**Comment by dannyzaken** [comment]
@nb-ohad is right. in that case we shouldn't change anything in the operator. setting the env on the core sts is enough

**Comment by romayalon** [comment]
that's correct, it can be done by a single env var. thanks :) 
closing

**Pull request closed without merging**
