### PR TITLE
[5.12] bump version 5.12.5

### PR DESCRIPTION
**Pull request by tangledbytes**
### Explain the changes
The title says it all.

### CODE REVIEW

**Review by dannyzaken — APPROVED** [review]

**Comment by utkarsh-pro** [comment]
@liranmauda, added the README changes as well.

**Comment by utkarsh-pro** [comment]
Something isn't right here. NooBaa core pod is crashing in the logs...

**Comment by liranmauda** [comment]
@utkarsh-pro can you please rebase this, and change it to 5.12.5 ?

**Comment by liranmauda** [comment]
Closing, We will redo it once we release a z stream on 5.12

**Pull request closed without merging**
