### PR TITLE
cli: Print on newline, if more than one value

### LINKED ISSUE #267: CLI | Status | When we have more than one ExternalDNS, each one should be in its own line
When we have more than one ExternalDNS, they appear in the same line which is confusing
We should print each address in its own line. 

root_vm-10-117___downstream_noobaa-operator

### PR DESCRIPTION
**Pull request by nik-redhat**
Signed-off-by: nik-redhat <nladha@redhat.com>

### Explain the changes
1. Added a new util function `PrettyPrint` to print each item of a string array in newline if the length is more than 1.

### Issues:
1. Fixed #267

### CODE REVIEW

**Comment by nik-redhat** [comment]
Sample output after the changes:
```
#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [ https://google.com,
		https://github.com,
		http://redhat.com ]
ExternalIP  : []
NodePorts   : [https://192.168.49.2:32369]
InternalDNS : [https://s3.default.svc:443]
InternalIP  : [https://10.110.79.142:443]
PodPorts    : [https://172.17.0.2:6443]
```

```
#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [https://google.com]
ExternalIP  : []
NodePorts   : [https://192.168.49.2:32369]
InternalDNS : [https://s3.default.svc:443]
InternalIP  : [https://10.110.79.142:443]
PodPorts    : [https://172.17.0.2:6443]
```

```
#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : []
ExternalIP  : []
NodePorts   : [https://192.168.49.2:32369]
InternalDNS : [https://s3.default.svc:443]
InternalIP  : [https://10.110.79.142:443]
PodPorts    : [https://172.17.0.2:6443]
```

**Comment by nik-redhat** [comment]
The `golangci-lint` test seems to be passing locally for me. Can't get what is causing the issue here :thinking:

**Review by liranmauda — APPROVED** [review]
LGTM

**Comment by baum** [comment]
Rebased another initially green PR today, and see there also this [golangci-lint error](https://github.com/noobaa/noobaa-operator/runs/7832820510?check_suite_focus=true).

**Pull request merged**
