### PR TITLE
Fix Bug #1040 | Add Namespace Option in DB-Dump (Not Only Default)

### LINKED ISSUE #1040: DB-Dump Not Generated In Test Namespace Using PG DB
### Environment info
NooBaa Operator Version: 5.13.0
Platform: Kubernetes 1.20.2 | minikube 1.18.1

### Actual behavior
1. DB-dump not generated.

### Expected behavior
1. Generate DB-dump, or at least inform the reason for the problem.

### Steps to reproduce
1. Use the steps in the workflow file to reproduce.

### More information - Screenshots / Logs / Other output

1. a [link](https://github.com/noobaa/noobaa-operator/actions/runs/4052201988/jobs/6971350284) to the failed job.
_Note: this link will be available under GH retention for saving the logs._
 
2. a Screenshot:
Screenshot 2023-01-31 at 15 03 39
 
3. logs:
[logs_15156.zip](https://github.com/noobaa/noobaa-operator/files/10546642/logs_15156.zip)
[admission-tests-logs.zip](https://github.com/noobaa/noobaa-operator/files/10546641/admission-tests-logs.zip)

### PR DESCRIPTION
**Pull request by shirady**
Signed-off-by: shirady <57721533+shirady@users.noreply.github.com>

### Explain the changes
1. Add namespace option in db-dump (not only default)

### Issues: Fixed #1040
1. Today db-dump works well only with the default namespace.

### Testing Instructions:
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - ‘Build images’.
2. Deploy Noobaa to a namespace that is different than the default (nb install -n test, for example).
3. Run: `nb diagnose --db-dump --dir=my-db-logs-test -n test`.
_Note: `nb` is a alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Comment by shirady** [comment]
The original fix is needed in line 76 in PG DB.
I also added the change in Mongo DB in line 129 (and I also saw it was used in lines 143, 260, and 268).
The rest of the changes were created automatically when I saved the file.

**Comment by shirady** [comment]
We have 2 kinds of DB:
1. **PG DB** - I worked on it (and opened the mentioned issue on it).
2. **MongoDB** - I tried to check the change (same change, adding namespace flag to exec functions) we didn't have errors, but I cannot see the new db-dump.

I'm closing the PR for now, later I can either open with PG DB change or keep investigating to have MongoDB fixed as well. @dannyzaken, WDYT?

**Comment by dannyzaken** [comment]
@shirady following our discussion, you can reopen this PR and ignore mongo for now (if there are gaps and mongo is not working correctly, then open an issue)

**Comment by shirady** [comment]
> @shirady following our discussion, you can reopen this PR and ignore mongo for now (if there are gaps and mongo is not working correctly, then open an issue)

I reopened it in PR #1060

**Pull request closed without merging**
